name: Example CICD Workflow with Node.js

on:
  push:
    branches: [master, develop]

jobs:
  ci_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./02_Node_Example

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24.11.0'
    
    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm run test
  
  cd_test:
    runs-on: ubuntu-latest
    needs: ci_test

    defaults:
      run:
        working-directory: ./02_Node_Example

    steps:
    - name: Checkout repository
      uses: actions/checkout@3

    - name: SSH by appleboy
      uses: appleboy/ssh-action@0.1.6

      with:
        host: ${{secrets.SSH_HOST}}
        usename: ${{secrets.SSH_USERNAME}}
        password: ${{secrets.SSH_PASSWORD}}
        port: ${{secrets.SSH_PORT}}
        script: |
          cd ..
          ls

  